package me.vrishab.auction.system;

public interface ErrorCode {
    String INVALID_ARGUMENTS = "INVALID_ARGUMENTS";
    String NOT_FOUND = "NOT_FOUND";
    String BAD_REQUEST = "BAD_REQUEST";
    String UNAUTHORIZED = "UNAUTHORIZED";
    String FORBIDDEN = "FORBIDDEN";
    String OPTIMISTIC_LOCKING_FAILURE = "OPTIMISTIC_LOCKING_FAILURE";
    String AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
    String ACCOUNT_DISABLED = "ACCOUNT_DISABLED";
    String INVALID_TOKEN = "INVALID_TOKEN";
    String AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED";
    String SERVER_ERROR = "SERVER_ERROR";
    
    // Domain specific
    String AUCTION_NOT_STARTED_OR_ENDED = "AUCTION_NOT_STARTED_OR_ENDED";
    String INVALID_BID_AMOUNT = "INVALID_BID_AMOUNT";
    String CONCURRENT_BID_ERROR = "CONCURRENT_BID_ERROR";
}
