spring:
  application:
    name: auction
  datasource:
    url: jdbc:h2:mem:auction
    driver-class-name: org.h2.Driver
    username: sa
    password:
    generate-unique-name: false
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

api:
  endpoint:
    base-url: /api/v4

server:
  port: 3000

logging:
  level:
    org:
      springframework:
        security: INFO