spring:
  application:
    name: auction
  datasource:
    url: jdbc:h2:mem:auction
    driver-class-name: org.h2.Driver
    username: sa
    password:
    generate-unique-name: false
#      show-sql: true

api:
  endpoint:
    base-url: /api/v1

logging:
  level:
    org:
      springframework:
        security: INFO