spring:
  application:
    name: auction
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379

api:
  endpoint:
    base-url: /api/v1

auction:
  bidding:
    lock-timeout-seconds: 30

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: INFO
