spring:
  application:
    name: auction
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

api:
  endpoint:
    base-url: /api/v1

auction:
  bidding:
    lock-timeout-seconds: 30
  cors:
    allowed-origin: ${ALLOWED_ORIGIN}

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: INFO
