name: Java CI with Gradle

on:
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Spring Gradle Build Action
        uses: spring-io/spring-gradle-build-action@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test with Gradle
        run: ./gradlew clean test
